#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/rancher-system-agent dist/artifacts/rancher-system-agent${SUFFIX}
cp install.sh dist/artifacts/install.sh
cp system-agent-uninstall.sh dist/artifacts/system-agent-uninstall.sh

IMAGE=${REPO}/system-agent:${TAG}-suc
DOCKERFILE=package/Dockerfile.suc
if [ -e ${DOCKERFILE}.suc.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.suc.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
