ARG ALPINE=alpine:3.11
FROM ${ALPINE} as kubectl
RUN apk add -U curl
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then ARCH=amd64; fi && \
    curl -L -o /usr/bin/kubectl https://dl.k8s.io/release/v1.21.0/bin/linux/${ARCH}/kubectl && \
    chmod +x /usr/bin/kubectl

ARG ALPINE=alpine:3.11
FROM ${ALPINE}

RUN mkdir /opt/rancher-system-agent-suc
COPY install.sh /opt/rancher-system-agent-suc/install.sh
COPY uninstall.sh /opt/rancher-system-agent-suc/uninstall.sh
COPY bin/rancher-system-agent /opt/rancher-system-agent-suc
COPY package/suc/run.sh /opt/rancher-system-agent-suc/run.sh
COPY --from=kubectl /usr/bin/kubectl /usr/bin/

ENTRYPOINT ["/opt/rancher-system-agent-suc/run.sh"]
