ARG IMG_VERSION=15.6

FROM registry.suse.com/bci/bci-micro:${IMG_VERSION} AS final

# Temporary build stage image
FROM registry.suse.com/bci/bci-base:${IMG_VERSION} AS builder

# Install system packages using builder image that has zypper
COPY --from=final / /chroot/

RUN zypper refresh && \
    zypper --installroot /chroot -n in --no-recommends \
    openssl patterns-base-fips grep && \
    zypper --installroot /chroot clean -a && \
    rm -rf /chroot/var/cache/zypp/* /chroot/var/log/zypp/* /chroot/tmp/* /chroot/var/tmp/* /chroot/usr/share/doc/packages/*

ARG KUBECTL_VERSION=v1.33.5

# https://dl.k8s.io/release/v1.33.5/bin/linux/arm64/kubectl.sha256
ENV KUBECTL_SUM_arm64=6db7c5d846c3b3ddfd39f3137a93fe96af3938860eefdbf2429805ee1656e381
# https://dl.k8s.io/release/v1.33.5/bin/linux/amd64/kubectl.sha256
ENV KUBECTL_SUM_amd64=6a12d6c39e4a611a3687ee24d8c733961bb4bae1ae975f5204400c0a6930c6fc

RUN zypper in -y curl openssl patterns-base-fips

RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then ARCH=amd64; fi && \
    if [ "$ARCH" = "aarch64" ]; then ARCH=arm64; fi && \
    curl -L -f -o kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${ARCH}/kubectl" && \
    install -o root -g root -m 0755 kubectl /chroot/usr/bin/kubectl && \
    KUBECTL_SUM="KUBECTL_SUM_${ARCH}" && echo "${!KUBECTL_SUM}  /chroot/usr/bin/kubectl" | sha256sum -c -
RUN /chroot/usr/bin/kubectl version --client

# Main stage using bci-micro as the base image
FROM final

# Copy binaries and configuration files from builder to micro
COPY --from=builder /chroot/ /

ENV CATTLE_AGENT_VAR_DIR="/var/lib/rancher/agent"

RUN mkdir /opt/rancher-system-agent-suc

COPY install.sh /opt/rancher-system-agent-suc/install.sh
COPY system-agent-uninstall.sh /opt/rancher-system-agent-suc/system-agent-uninstall.sh
COPY bin/rancher-system-agent /opt/rancher-system-agent-suc
COPY package/suc/run.sh /opt/rancher-system-agent-suc/run.sh
RUN chmod +x /opt/rancher-system-agent-suc/rancher-system-agent

ENTRYPOINT ["/opt/rancher-system-agent-suc/run.sh"]
